#nome = str(input('Qual é o seu nome? '))
nome = str(input('Qual é o seu nome? ')).strip()
print('O seu nome em maiúsculo é {}.'.format(nome.upper()))
print('O seu nome é minúsculo é {}.'.format(nome.lower()))
#replace = nome.replace(' ', '')
#print('O seu nome tem {} letras.'.format(len(replace)))
print('O seu nome tem {} letras.'.format(len(nome) - nome.count(' ')))
split = nome.split()
print('O seu primeiro nome tem {} letras.'.format(len(split[0])))
print('O seu primeiro nome tem {} letras.'.format(nome.find(' ')))